- name: Script orchestration with user permission
  hosts: local
  tasks:
    - name: Organization of files by extensions
      script: ~/Documentos/TOOLBOX_Luanix/scripts/files_organization.sh # full directory path
      
    - name: Backup of files of main directories
      script: ~/Documentos/TOOLBOX_Luanix/scripts/files_backup.sh # full directory path