- name: Script orchestration with administrator permission
  hosts: local
  become: yes
  tasks:
    - name: Update and upgrade packages, remove orphaned dependencies and clean old packages
      script: ~/Documentos/TOOLBOX_Luanix/scripts/update_clean.sh # full directory path

    - name: Update, upgrade and install packages
      script: ~/Documentos/TOOLBOX_Luanix/scripts/update_install.sh # full directory path

    - name: Update and upgrade packages, remove orphaned dependencies and clean old packages again
      script: ~/Documentos/TOOLBOX_Luanix/scripts/update_clean.sh # full directory path